### ISSUE TITLE
Great but algorithim need improving

### ISSUE THREAD

**Issue by CGRoffcialcode** [LiamKrenn/beltmatic#2]
The algorithm that you coded uses the extraction sources and finds possible ways to add it. But this algorithm ONLY looks for available extraction sources, its not as complex. It would be better if you could improve how the algorithm works. 
I couldnt yet open a pr but ill try later.
EDIT: i dont know typescript oof soo i dont understand the code
FOR EXAMPLE: 
![image](https://github.com/user-attachments/assets/f30efaac-91e6-4ecd-b203-6a09519a8e91)

**Comment by LiamKrenn** [comment]
You are right, the algorithm only uses the available sources, as it would become a lot more computationally intense and in your given example, it wouldn't even be more efficient. Of course there will be cases where it's better to use newly created numbers, however I don't think I'll work on a feature like this in the algorithm in the near future. Feel free to create a PR - it's probably a good opportunity to learn TS, as it isn't that much different from JS ;)

**Comment by CGRoffcialcode** [comment]
true, i think ill close this issue

**Comment by LiamKrenn** [comment]
I think you can leave this open, as this is something that could be added

**Comment by LiamKrenn** [comment]
Now that I have thought about it, I think I have an idea, if I have time in the upcoming days I'll try to implement it

**Comment by LiamKrenn** [comment]
Hey there, just pushed the feature with reusing generated values. This can actually generate shorter solutions! Thanks for raising this issue.

**Comment by CGRoffcialcode** [comment]
Welcome 🫡
